export const LOAD_DASHBOARD = 'LOAD_DASHBOARD';
export const ENTITIES_CHANGED = 'ENTITIES_CHANGED';
export const DASHBOARD_LOADED = 'DASHBOARD_LOADED';
export const LOAD_NOTE = 'NOTE_LOADED';
export const NOTE_LOADED = 'NOTE_LOADED';